---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/courses/{course_id}/author":
    parameters:
    - name: course_id
      in: path
      description: course_id
      required: true
      schema:
        type: string
    get:
      summary: show_related_resource author
      responses:
        '200':
          description: successful
  "/authors/{author_id}/relationships/courses":
    parameters:
    - name: author_id
      in: path
      description: author_id
      required: true
      schema:
        type: string
    get:
      summary: show_relationship author
      responses:
        '200':
          description: successful
    post:
      summary: create_relationship author
      parameters: []
      responses:
        '204':
          description: successful
  "/authors":
    get:
      summary: list authors
      responses:
        '200':
          description: successful
    post:
      summary: create author
      parameters: []
      responses:
        '201':
          description: successful
      requestBody:
        content:
          application/vnd.api+json:
            schema:
              "$ref": "#/components/schemas/new_object"
  "/authors/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show author
      responses:
        '200':
          description: successful
    patch:
      summary: update author
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/vnd.api+json:
            schema:
              "$ref": "#/components/schemas/object"
    put:
      summary: update author
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/vnd.api+json:
            schema:
              "$ref": "#/components/schemas/object"
    delete:
      summary: delete author
      responses:
        '204':
          description: successful
  "/courses/{course_id}/relationships/author":
    parameters:
    - name: course_id
      in: path
      description: course_id
      required: true
      schema:
        type: string
    get:
      summary: show_relationship course
      responses:
        '200':
          description: successful
    patch:
      summary: update_relationship course
      parameters: []
      responses:
        '204':
          description: successful
    delete:
      summary: destroy_relationship course
      responses:
        '422':
          description: successful
  "/courses/{course_id}/relationships/talents":
    parameters:
    - name: course_id
      in: path
      description: course_id
      required: true
      schema:
        type: string
    get:
      summary: show_relationship course
      responses:
        '200':
          description: successful
    post:
      summary: create_relationship course
      parameters: []
      responses:
        '204':
          description: successful
    delete:
      summary: destroy_relationship course
      parameters: []
      responses:
        '204':
          description: successful
  "/courses":
    get:
      summary: list courses
      responses:
        '200':
          description: successful
    post:
      summary: create course
      parameters: []
      responses:
        '201':
          description: successful
      requestBody:
        content:
          application/vnd.api+json:
            schema:
              "$ref": "#/components/schemas/object"
  "/courses/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show course
      responses:
        '200':
          description: successful
    patch:
      summary: update course
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/vnd.api+json:
            schema:
              "$ref": "#/components/schemas/object"
    put:
      summary: update course
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/vnd.api+json:
            schema:
              "$ref": "#/components/schemas/object"
    delete:
      summary: delete course
      responses:
        '204':
          description: successful
  "/authors/{author_id}/courses":
    parameters:
    - name: author_id
      in: path
      description: author_id
      required: true
      schema:
        type: string
    get:
      summary: index_related_resources course
      responses:
        '200':
          description: successful
  "/talents/{talent_id}/courses":
    parameters:
    - name: talent_id
      in: path
      description: talent_id
      required: true
      schema:
        type: string
    get:
      summary: index_related_resources course
      responses:
        '200':
          description: successful
  "/courses/{course_id}/talents":
    parameters:
    - name: course_id
      in: path
      description: course_id
      required: true
      schema:
        type: integer
    get:
      summary: index_related_resources talent
      responses:
        '200':
          description: successful
  "/talents/{talent_id}/relationships/courses":
    parameters:
    - name: talent_id
      in: path
      description: talent_id
      required: true
      schema:
        type: string
    get:
      summary: show_relationship talent
      responses:
        '200':
          description: successful
    post:
      summary: create_relationship talent
      parameters: []
      responses:
        '204':
          description: successful
  "/talents":
    get:
      summary: list talents
      responses:
        '200':
          description: successful
    post:
      summary: create talent
      parameters: []
      responses:
        '201':
          description: successful
      requestBody:
        content:
          application/vnd.api+json:
            schema:
              "$ref": "#/components/schemas/new_object"
  "/talents/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show talent
      responses:
        '200':
          description: successful
    patch:
      summary: update talent
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/vnd.api+json:
            schema:
              "$ref": "#/components/schemas/object"
    put:
      summary: update talent
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/vnd.api+json:
            schema:
              "$ref": "#/components/schemas/object"
    delete:
      summary: delete talent
      responses:
        '204':
          description: successful
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
components:
  schemas:
    object:
      type: object
      properties:
        data:
          type: object
          properties:
            type:
              type: string
            id:
              type: integer
            attributes:
              type: object
              properties:
                name:
                  type: string
      required:
      - id
      - name
    new_object:
      type: object
      properties:
        data:
          type: object
          properties:
            type:
              type: string
            attributes:
              type: object
              properties:
                name:
                  type: string
      required:
      - name
